### ISSUE TITLE
imp package is removed from python 3.12

### ISSUE THREAD

**Issue by h-oll** [matrix-org/pantalaimon#176]
Pantalaimon cannot be installed on systems with python 3.12 as it references the `imp` package that has been removed and replaced by `importlib`.

**Comment by chookity-pokk** [comment]
Sorry for the delayed response @h-oll, thanks for the report! I will check that out later today and get that fixed!

**Comment by chookity-pokk** [comment]
@h-oll Can you give a bit of information on how you installed the package? I just built master from source by creating a new `conda` environment and running `pip install .` and it was able to build just fine. I also don't see any reference to the `imp` package anywhere in the repo so a full stack trace would be helpful.

**Comment by RedChops** [comment]
Looks like this happens because an old version of `matrix_nio` is installed. I'm able to run `pip install matrix_nio==0.25.2` which makes that error go away, but warns of a compatibility error (does not affect anything it would seem). I arbitrarily picked 0.25.2, you could probably use the newest version just fine

**Comment by chookity-pokk** [comment]
@RedChops Thanks for the info! I opened a PR with the updated version of `matrix_nio` and will merge that tomorrow if there aren't objections.

**Comment by chookity-pokk** [comment]
Fixed with #178!
