### ISSUE TITLE
Support media uploads

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/pantalaimon#70]
Which is a bit tricky, since media uploads *should* be encrypted for room messages, but left alone for everything else. Perhaps the easiest fix is an additional query parameter to ask for an event to be encrypted. It's a bit tricky because it means clients will need to know to do this, but otoh, I don't seen an alternative.

**Comment by poljar** [comment]
The thing I had in mind is a bit different:

1. Receive an upload normally, return a fake mxc URI but don't upload anything yet.
2. Once the client posts a message that contains the fake mxid figure out if it needs to be encrypted or not, complete the upload now 
3. Modify the content to contain the correct mxid.

This of course is tricky and has a bunch of assumptions, though your alternative requires clients to get support for this and Pantalaimon is meant to be a transparent proxy.

**Comment by Half-Shot** [comment]
Hadn't thought about it like that. Works, but it means you will need to do a true upload for user/room avatars

**Comment by aspacca** [comment]
much looking for this feature.
@poljar if you give me some hints I can try to open a PRs according to your solution, thanks

**Comment by poljar** [comment]
You can take a look how the `/download` endpoint was added over here https://github.com/matrix-org/pantalaimon/commit/4dac44cfd71064e3d2b4ba2d1c21e5d176f79f0e.

We need to add a new endpoint that matches the behavior defined in the [spec](https://matrix.org/docs/spec/client_server/latest#post-matrix-media-r0-upload).

Since we're going to generate fake mxc URIs we're going to need to store a mapping from the fake one to the real one. This patch adds a new SQL table to the store https://github.com/matrix-org/pantalaimon/commit/d25989cfd72a9573250c744572ded6a34b4a3feb.

You're gonna have to experiment a bit and see how clients behave. 

The idea is to catch the upload and return a fake MXC, then watch if the client will post a room event which contains this fake MXC, this should probably have some timeout. Only then do we decide if we're going to encrypt the MXC or not.

1. Room is encrypted: Encrypt the data, upload the data for real and modify the event to contain the real MXC and the json token.
2. Room is not encrypted: Upload the data for real and modify the event to contain the real MXC
3. If the client tries to GET the MXC before posting a message we upload it without encrypting as well.

Store the mapping from fake -> real MXC, so if the client tries to download the fake one we can return the real data instead.

I think we're going to need to watch for profile changes as well but we can leave implementing this for a later stage while writing this.

**Comment by aspacca** [comment]
1. https://matrix.org/docs/spec/client_server/latest#post-matrix-media-r0-upload
first issue I see here is that we cannot return other than 200 status code, since all the 4xx one can happen only when actually uploading the media. is this fine?
what do we do on the second step? when the client post a room event with the fake MXC and the actual upload returns a 4xx?

2. https://github.com/matrix-org/pantalaimon/commit/d25989cfd72a9573250c744572ded6a34b4a3feb
I should add a new SQL table to the store for the mapping between the fake mxc url and the real one. also storing the content body of the media to cache until we do the real upload or the client tries do download the fake mxc url. is this correct?

3. https://github.com/matrix-org/pantalaimon/blob/9c65c060754c2c1fa7bdf2a5acc4812a260158dc/pantalaimon/client.py#L307
is it fine to add here before sending to the queue the following logic:
- check for `{event_type}` and eventually `msgtype`
- extract `content.url` from the message and check if it's a not expired matching fake mxc url
- if the previous is true check the status of the room (encrypted or not: any helper for this?) and proceed to the upload encrypted or not
- if not encrypted replace the `content.url` with the real mxc
- if encrypted add `content.file` with its payload (how I do generate key, iv and hashes?)


> If the client tries to GET the MXC before posting a message we upload it without encrypting as well.

this is in the download endpoint, is it?

last question: what format do we give to the fake MXC? I would override the `mxc_server` suffixing it with a safe TLD (I have to investigate on this, but I guess there's a reserved TLD for cases such this)

**Comment by poljar** [comment]
>  1. https://matrix.org/docs/spec/client_server/latest#post-matrix-media-r0-upload
>  first issue I see here is that we cannot return other than 200 status code, since all the 4xx one can happen only when actually uploading the media. is this fine?

That is a problem and I'm not really sure what to do here. One option is to ignore the problem, the other is to always upload an encrypted version and use that as the fake MXC. Perhaps we should just do that, though it does sound a bit wasteful.

>  2. [d25989c](https://github.com/matrix-org/pantalaimon/commit/d25989cfd72a9573250c744572ded6a34b4a3feb)
>  I should add a new SQL table to the store for the mapping between the fake mxc url and the real one. also storing the content body of the media to cache until we do the real upload or the client tries do download the fake mxc url. is this correct?

If we always upload encrypted data, storing the content body won't be necessary. So I guess that's another argument for always uploading.

> 3. https://github.com/matrix-org/pantalaimon/blob/9c65c060754c2c1fa7bdf2a5acc4812a260158dc/pantalaimon/client.py#L307
> is it fine to add here before sending to the queue the following logic:

No, the UI thread is the dbus thread that makes sure that `panctl` works. The message sending is happening over here https://github.com/matrix-org/pantalaimon/blob/master/pantalaimon/daemon.py#L866
> 
>     * check for `{event_type}` and eventually `msgtype`
> 
>     * extract `content.url` from the message and check if it's a not expired matching fake mxc url
> 
>     * if the previous is true check the status of the room (encrypted or not: any helper for this?) and proceed to the upload encrypted or not

You can fetch the `MatrixRoom` object out of the client there and it will have a `encrypted` attribute which is a boolean flag tracking if the room is encrypted or not.

```python
room = client.rooms[room_id]
print(room.encrypted)
```
Careful though, the room might not exist.

>     * if not encrypted replace the `content.url` with the real mxc
> 
>     * if encrypted add `content.file` with its payload (how I do generate key, iv and hashes?)

You don't, nio does that for you with the [upload](https://matrix-nio.readthedocs.io/en/latest/nio.html#nio.AsyncClient.upload) method. The return value is a tuple containing the response and the key, hash, etc...

> Returns a tuple containing:
> Either a UploadResponse if the request was successful, or a UploadError if there was an error with the request
> A dict with file decryption info if encrypt is True, else None.

This is what the docs say.

> > If the client tries to GET the MXC before posting a message we upload it without encrypting as well.
> 
> this is in the download endpoint, is it?
> 

Yes, one of the commits I gave earlier already has some logic that handles this request. Some additional logic will be needed there.

> last question: what format do we give to the fake MXC? I would override the `mxc_server` suffixing it with a safe TLD (I have to investigate on this, but I guess there's a reserved TLD for cases such this)

Another argument for always uploading an encrypted version of the data :).

**Comment by aspacca** [comment]
here a draft: https://github.com/matrix-org/pantalaimon/pull/79

**Comment by aspacca** [comment]
>>> If the client tries to GET the MXC before posting a message we upload it without encrypting as well.
>> this is in the download endpoint, is it?
> Yes, one of the commits I gave earlier already has some logic that handles this request. Some additional logic will be needed there.

still missing this part

**Comment by poljar** [comment]
Closed by #79.
